/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2b67c9358ea41396cdcaa21f4e9a0089)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	FREE_RL: RateLimit;
	APP_BASE_URL: "https://tariff.watch";
	BILLING_MODE: "free_launch";
	STRIPE_PRICE_ID: "price_1Th6raRtNOtWEuKvU7fGbHym";
	STRIPE_METER_EVENT_NAME: "tariff_watch_requests";
	PRO_MONTHLY_QUOTA: 1000000;
	FREE_CALL_ALLOWANCE: 30;
	SIGNUP_CREDIT_CENTS: 300;
	STRIPE_FIXED_MONTHLY_PRICE_ID: "price_1ThAO2RtNOtWEuKv0LUVQTiV";
	STRIPE_FIXED_MONTHLY_METERED_PRICE_ID: "price_1ThNg8RtNOtWEuKv2ROZRlIr";
	STRIPE_FIXED_ANNUAL_PRICE_ID: "price_REPLACE_ME";
	STRIPE_FIXED_ANNUAL_METERED_PRICE_ID: "price_REPLACE_ME";
	FIXED_MONTHLY_INCLUDED_CALLS: 500;
	FIXED_ANNUAL_INCLUDED_CALLS: 7500;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "BILLING_MODE" | "STRIPE_PRICE_ID" | "STRIPE_METER_EVENT_NAME" | "PRO_MONTHLY_QUOTA" | "FREE_CALL_ALLOWANCE" | "SIGNUP_CREDIT_CENTS" | "STRIPE_FIXED_MONTHLY_PRICE_ID" | "STRIPE_FIXED_MONTHLY_METERED_PRICE_ID" | "STRIPE_FIXED_ANNUAL_PRICE_ID" | "STRIPE_FIXED_ANNUAL_METERED_PRICE_ID" | "FIXED_MONTHLY_INCLUDED_CALLS" | "FIXED_ANNUAL_INCLUDED_CALLS" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "ADMIN_TOKEN">> {}
}
