/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6f61b2dd8b3d692398251dd9781f6fab)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_BASE_URL: "https://tariff.watch";
	STRIPE_PRICE_ID: "price_1TgZDxRvagOb6JQr6AApWs1l";
	PRO_MONTHLY_QUOTA: 10000;
	FREE_MONTHLY_QUOTA: 250;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "STRIPE_PRICE_ID" | "PRO_MONTHLY_QUOTA" | "FREE_MONTHLY_QUOTA" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "ADMIN_TOKEN">> {}
}
