/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 22f35cd4ffa38fef42c6c0a495feb881)
interface __BaseEnv_Env {
	RAW: R2Bucket;
	DB: D1Database;
	APP_BASE_URL: "http://localhost:8787";
	BILLING_MODE: "free_launch";
	STRIPE_PRICE_ID: "price_REPLACE_ME";
	STRIPE_FIXED_MONTHLY_PRICE_ID: "price_REPLACE_ME";
	STRIPE_FIXED_MONTHLY_METERED_PRICE_ID: "price_REPLACE_ME";
	STRIPE_FIXED_ANNUAL_PRICE_ID: "price_REPLACE_ME";
	STRIPE_FIXED_ANNUAL_METERED_PRICE_ID: "price_REPLACE_ME";
	PRO_MONTHLY_QUOTA: 10000;
	FREE_CALL_ALLOWANCE: 30;
	SIGNUP_CREDIT_CENTS: 300;
	FIXED_MONTHLY_INCLUDED_CALLS: 500;
	FIXED_ANNUAL_INCLUDED_CALLS: 7500;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "BILLING_MODE" | "STRIPE_PRICE_ID" | "STRIPE_FIXED_MONTHLY_PRICE_ID" | "STRIPE_FIXED_MONTHLY_METERED_PRICE_ID" | "STRIPE_FIXED_ANNUAL_PRICE_ID" | "STRIPE_FIXED_ANNUAL_METERED_PRICE_ID" | "PRO_MONTHLY_QUOTA" | "FREE_CALL_ALLOWANCE" | "SIGNUP_CREDIT_CENTS" | "FIXED_MONTHLY_INCLUDED_CALLS" | "FIXED_ANNUAL_INCLUDED_CALLS">> {}
}
