/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a83480622503eb4c9a632f13dce173db)
interface __BaseEnv_Env {
	RAW: R2Bucket;
	DB: D1Database;
	APP_BASE_URL: "http://localhost:8787";
	STRIPE_PRICE_ID: "price_REPLACE_ME";
	PRO_MONTHLY_QUOTA: 10000;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "STRIPE_PRICE_ID" | "PRO_MONTHLY_QUOTA">> {}
}
